// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAutoStartStatus():Promise<boolean>;

export function GetProxyConfig():Promise<main.ProxyConfig>;

export function GetProxyServerPort():Promise<number>;

export function GetProxyURL():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function IsAutoStartEnabled():Promise<boolean>;

export function OpenURL(arg1:string):Promise<void>;

export function ProxyRequest(arg1:string):Promise<string>;

export function SaveFileToDownloads(arg1:string,arg2:string):Promise<string>;

export function SetProxyConfig(arg1:main.ProxyConfig):Promise<void>;

export function StartProxyServer():Promise<void>;

export function StopProxyServer():Promise<void>;

export function TestProxyConnection():Promise<boolean>;

export function ToggleAutoStart():Promise<boolean>;
