// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAutoStartStatus() {
  return window['go']['main']['App']['GetAutoStartStatus']();
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetProxyServerPort() {
  return window['go']['main']['App']['GetProxyServerPort']();
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProxyRequest(arg1) {
  return window['go']['main']['App']['ProxyRequest'](arg1);
}

export function SaveFileToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveFileToDownloads'](arg1, arg2);
}

export function SetProxyConfig(arg1) {
  return window['go']['main']['App']['SetProxyConfig'](arg1);
}

export function StartProxyServer() {
  return window['go']['main']['App']['StartProxyServer']();
}

export function StopProxyServer() {
  return window['go']['main']['App']['StopProxyServer']();
}

export function TestProxyConnection() {
  return window['go']['main']['App']['TestProxyConnection']();
}

export function ToggleAutoStart() {
  return window['go']['main']['App']['ToggleAutoStart']();
}
