// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearClipboardHistory() {
  return window['go']['main']['App']['ClearClipboardHistory']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GetAutoStartStatus() {
  return window['go']['main']['App']['GetAutoStartStatus']();
}

export function GetClipboardHistory() {
  return window['go']['main']['App']['GetClipboardHistory']();
}

export function GetClipboardHistoryPage(arg1, arg2) {
  return window['go']['main']['App']['GetClipboardHistoryPage'](arg1, arg2);
}

export function GetMaxRecords() {
  return window['go']['main']['App']['GetMaxRecords']();
}

export function GetProxyConfig() {
  return window['go']['main']['App']['GetProxyConfig']();
}

export function GetProxyServerPort() {
  return window['go']['main']['App']['GetProxyServerPort']();
}

export function GetProxyURL() {
  return window['go']['main']['App']['GetProxyURL']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function OpenClipboardFile() {
  return window['go']['main']['App']['OpenClipboardFile']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ProxyRequest(arg1) {
  return window['go']['main']['App']['ProxyRequest'](arg1);
}

export function RemoveClipboardItem(arg1) {
  return window['go']['main']['App']['RemoveClipboardItem'](arg1);
}

export function SaveFileToDownloads(arg1, arg2) {
  return window['go']['main']['App']['SaveFileToDownloads'](arg1, arg2);
}

export function SetMaxRecords(arg1) {
  return window['go']['main']['App']['SetMaxRecords'](arg1);
}

export function SetProxyConfig(arg1) {
  return window['go']['main']['App']['SetProxyConfig'](arg1);
}

export function StartProxyServer() {
  return window['go']['main']['App']['StartProxyServer']();
}

export function StopProxyServer() {
  return window['go']['main']['App']['StopProxyServer']();
}

export function TestProxyConnection() {
  return window['go']['main']['App']['TestProxyConnection']();
}

export function ToggleAutoStart() {
  return window['go']['main']['App']['ToggleAutoStart']();
}
